version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__host=database
      - database__connection__user=root
      - database__connection__password=root
      - database__connection__database=ghost
    depends_on:
      - database
    networks:
      - my-network
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data: